// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/lh/github/test-demo/node_modules/.pnpm/@umijs+renderer-react@4.0.86_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/lh/github/test-demo/node_modules/.pnpm/@umijs+renderer-react@4.0.86_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/lh/github/test-demo/node_modules/.pnpm/umi@4.0.86_@babel+core@7.23.2_@types+react@18.2.28_eslint@8.35.0_postcss@8.4.31_prettier@2.8._nofmoycdhodhl3zayelubllxli/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/lh/github/test-demo/src/.umi/plugin-access';
export { Provider, useModel } from 'D:/lh/github/test-demo/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/lh/github/test-demo/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/lh/github/test-demo/src/.umi/plugin-access/types.d';
export * from 'D:/lh/github/test-demo/src/.umi/plugin-antd/types.d';
export * from 'D:/lh/github/test-demo/src/.umi/plugin-layout/types.d';
export * from 'D:/lh/github/test-demo/src/.umi/plugin-request/types.d';
