// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, Helmet, useAppData, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/demo/github/test-demo/node_modules/.pnpm/@umijs+renderer-react@4.0.34_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/demo/github/test-demo/node_modules/.pnpm/@umijs+renderer-react@4.0.34_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/demo/github/test-demo/node_modules/.pnpm/umi@4.0.34_@babel+core@7.23.2_@types+react@18.0.0_eslint@8.15.0_postcss@8.4.31_prettier@2.7.1_2h362ewdb2nvvr5jsghsr7twjq/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/demo/github/test-demo/src/.umi/plugin-access';
export { Provider, useModel } from 'D:/demo/github/test-demo/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/demo/github/test-demo/src/.umi/plugin-request';
export { proxy, useSnapshot, snapshot, subscribe, proxyWithComputed, proxyWithHistory, proxyWithDevtools, proxyMap, proxySet } from 'D:/demo/github/test-demo/src/.umi/plugin-valtio';
// plugins types.d.ts
export * from 'D:/demo/github/test-demo/src/.umi/plugin-layout/types.d';
export * from 'D:/demo/github/test-demo/src/.umi/plugin-request/types.d';
export { defineApp } from './core/defineApp'
export type {  RuntimeConfig } from './core/defineApp'
